CREATE TABLE IF NOT EXISTS Alumnos (
  matricula VARCHAR(10) PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,	
  Apellido_P VARCHAR(50) NOT NULL,
  Edad INT NOT NULL, 
  Genero VARCHAR(1) NOT NULL, 
  Trabajas BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS Planteles (
  Plantel VARCHAR(10) PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,	
  Direccion VARCHAR(100) NOT NULL,
  Tamano VARCHAR(15) NOT NULL
);
